version: 2.1
parameters:
    repo:
        type: string
        default: "rsksmart/rskj.git"
    version:
        type: string
        default: "3.0.0-SNAPSHOT"
    branch:
        type: string
        default: "master"
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk

    working_directory: ~/tmp

    steps:
      - checkout
      - run:
          name: Avoid hosts unknown for github
          command: mkdir -p ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
      - run:
          name: Clone and Build RSKj
          command: |
                    GIT_SSH_COMMAND='ssh -i ~/.ssh/id_rsa_fingerprint'
                    git clone -b << pipeline.parameters.branch >> git@github.com:<< pipeline.parameters.repo >> ~/rsksmart/rskj
                    cd ~/rsksmart/rskj/
                    ./configure.sh
                    ./gradlew clean build -x test

      - run:
          name: Prepare npm
          command: |
                    sudo apt-get update -y
                    sudo apt-get install -y apt-utils
                    curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
                    sudo apt update
                    sudo apt-get upgrade
                    sudo apt-get install -yf nodejs
                    sudo apt install build-essential

      - run:
          name: Start RskJ & Run Tests
          command: |
                    npm install
                    java -cp ~/rsksmart/rskj/rskj-core/build/libs/rskj-core-<< pipeline.parameters.version >>-all.jar co.rsk.Start --regtest nohup &               
                    until nc -z 127.0.0.1 4444
                    do
                      echo "Waiting for RskJ..."
                      sleep 1
                    done
                    npm test

      - store_test_results:
          path: ~/tmp/Results
      
      - store_artifacts:
          path: ~/tmp/Results/mocha
        
workflows:
    commit:
        jobs:
            - build
    daily:
        triggers:
            - schedule:
                cron: "21 01 * * *"
                filters:
                    branches:
                        only:
                            - master
        jobs:
            - build
