version: 2.1
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk

    working_directory: ~/tmp

    steps:
      - run:
          name: Avoid hosts unknown for github
          command: mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
      - run:
          name: Clone and Build RSKj
          command: |
                    GIT_SSH_COMMAND='ssh -i ~/.ssh/id_rsa_fingerprint'
                    git clone git@github.com:rsksmart/rskj.git ~/rsksmart/rskj
                    cd ~/rsksmart/rskj/
                    ./configure.sh
                    ./gradlew clean build -x test
      - run:
          name: Start RSKj & Run tests
          command: |
                    java -cp ~/rsksmart/rskj/rskj-core/build/libs/rskj-core-1.1.0-SNAPSHOT-all.jar co.rsk.Start --regtest nohup &               
                    until nc -z 127.0.0.1 4444
                    do
                      echo "Waiting for RskJ..."
                      sleep 1
                    done
                    sudo apt-get install nodejs
                    sudo ln -s /usr/local/bin/node /usr/bin/node
                    sudo ln -s /usr/local/lib/node /usr/lib/node
                    sudo ln -s /usr/local/bin/npm /usr/bin/npm
                    sudo ln -s /usr/local/bin/node-waf /usr/bin/node-waf
                    npm install
                    npm test

                      
workflows:
    commit:
        jobs:
            - build
    daily:
        triggers:
            - schedule:
                cron: "33 01 * * *"
                filters:
                    branches:
                        only:
                            - master
        jobs:
            - build
